lab1.elf: lab1.cc tasks.hh
	g++ lab1.cc -D TASK1 -o lab1.elf

t1:
	g++ lab1.cc -D TASK1 -o lab1.elf
	./lab1.elf

t2:
	g++ lab1.cc -D TASK2 -o lab1.elf
	./lab1.elf

t3:
	g++ lab1.cc -D TASK3 -o lab1.elf
	./lab1.elf

t4:
	g++ lab1.cc -D TASK4 -o lab1.elf
	./lab1.elf

clean:
	rm *.elf
